### ISSUE TITLE
Configure Chart Widget

### ISSUE THREAD

**Issue by jasonkeicher** [rajbos/GHAzDo-widget#18]
I am not getting a "configure" option for the chart widget.

![Image](https://github.com/rajbos/GHAzDo-widget/assets/3915176/0a855f5d-72e8-4b2d-a190-5c1978714493)

PS - this is great!

**Comment by rajbos** [comment]
Thanks for letting me know @jasonkeicher! Can you double check that you are on version `0.0.1.6`? I pushed an update earlier today to fix that.

**Comment by rajbos** [comment]
I figured out why this was happening (wrong config in the extension settings) and pushed a new release @jasonkeicher. 

Fixed in #21 and released in [0.0.1.7](https://github.com/rajbos/GHAzDo-widget/releases/tag/0.0.1.7).

Closing the issue as fixed.
