### ISSUE TITLE
Allow for custom colors per alert type

### ISSUE THREAD

**Issue by PagelsR** [rajbos/GHAzDo-widget#28]

**Comment by rajbos** [comment]
Added it in [Release 0.0.1.14](https://github.com/rajbos/GHAzDo-widget/releases/tag/0.0.1.14) @PagelsR!
You can now personalize the number widgets:

![image](https://github.com/rajbos/GHAzDo-widget/assets/6085745/be8d966a-dccb-41cc-b359-cb15341354a6)
