### ISSUE TITLE
Does not work with repositories having a space in them 

### ISSUE THREAD

**Issue by woeterman94** [rajbos/GHAzDo-widget#44]
Mijn Application Monorepo becomes "Mijn". 
![image](https://github.com/rajbos/GHAzDo-widget/assets/5755057/359b0d47-e061-46b9-bf22-6c743cb01066)

![image](https://github.com/rajbos/GHAzDo-widget/assets/5755057/77549daa-8967-4251-9314-3f2f44b0e1a3)

**Comment by rajbos** [comment]
I've released version 0.0.0.20 to fix this @woeterman94, thanks for the report !
